set(_CATKIN_CURRENT_PACKAGE "mbot")
set(mbot_VERSION "0.0.0")
set(mbot_MAINTAINER "zhang <zhang@todo.todo>")
set(mbot_PACKAGE_FORMAT "2")
set(mbot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "gazebo_ros" "urdf" "xacro")
set(mbot_BUILD_EXPORT_DEPENDS "urdf" "xacro")
set(mbot_BUILDTOOL_DEPENDS "catkin")
set(mbot_BUILDTOOL_EXPORT_DEPENDS )
set(mbot_EXEC_DEPENDS "urdf" "xacro" "geometry_msgs" "roscpp" "rospy" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control")
set(mbot_RUN_DEPENDS "urdf" "xacro" "geometry_msgs" "roscpp" "rospy" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control")
set(mbot_TEST_DEPENDS )
set(mbot_DOC_DEPENDS )
set(mbot_URL_WEBSITE "")
set(mbot_URL_BUGTRACKER "")
set(mbot_URL_REPOSITORY "")
set(mbot_DEPRECATED "")