set(_CATKIN_CURRENT_PACKAGE "robot_move")
set(robot_move_VERSION "0.0.0")
set(robot_move_MAINTAINER "zhang <zhang@todo.todo>")
set(robot_move_PACKAGE_FORMAT "2")
set(robot_move_BUILD_DEPENDS "actionlib" "actionlib_msgs" "message_generation")
set(robot_move_BUILD_EXPORT_DEPENDS "message_generation")
set(robot_move_BUILDTOOL_DEPENDS "catkin")
set(robot_move_BUILDTOOL_EXPORT_DEPENDS )
set(robot_move_EXEC_DEPENDS "message_runtime" "actionlib" "actionlib_msgs")
set(robot_move_RUN_DEPENDS "message_runtime" "actionlib" "actionlib_msgs" "message_generation")
set(robot_move_TEST_DEPENDS )
set(robot_move_DOC_DEPENDS )
set(robot_move_URL_WEBSITE "")
set(robot_move_URL_BUGTRACKER "")
set(robot_move_URL_REPOSITORY "")
set(robot_move_DEPRECATED "")