<?xml version="1.0"?>
<robot name="xbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>  
    <xacro:property name="wheel_mass"   value="0.5" />
    <xacro:property name="wheel_radius" value="0.0375"/>
    <xacro:property name="wheel_length" value="0.04"/>  
    <xacro:property name="wheel_joint_x" value="0.115"/>
    <xacro:property name="wheel_joint_y" value="0.1625"/>
    <xacro:property name="wheel_joint_z" value="0.04"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>

    <!-- Macro for inertia matrix -->

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" /> 
        </inertial>
    </xacro:macro>

    
    <!-- Macro for robot wheel -->
    <xacro:macro name="wheel" params="prefix prefix1 reflect reflect1">
        <joint name="${prefix}_${prefix1}_wheel_joint" type="continuous">
            <origin xyz="${reflect*wheel_joint_x} ${reflect1*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_${prefix1}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_${prefix1}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="yellow" />
            </visual>
       <collision>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
       </collision>
            <cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>

        <gazebo reference="${prefix}_${prefix1}_wheel_link">
            <material>Gazebo/Gray</material>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${prefix}_${prefix1}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_${prefix1}_wheel_joint" >
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_${prefix1}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

        <xacro:wheel prefix="left" prefix1="front" reflect="1" reflect1="1"/>
        <xacro:wheel prefix="right" prefix1="back" reflect="-1" reflect1="-1"/>
        <xacro:wheel prefix="left" prefix1="back" reflect="-1" reflect1="1"/>
        <xacro:wheel prefix="right" prefix1="front" reflect="1" reflect1="-1"/>     


<!-- Macro for robot xbot_base -->
    <xacro:macro name="xbot_support">

 <link name="support_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                     <box size="0.1 0.12 0.148" />
                </geometry>
                <material name="gray" />
            </visual>

            <collision>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.1 0.12 0.148" />
                </geometry>
            </collision> 

        <inertial>
            <mass value="0.2" />
            <inertia ixx="0.005372992" ixy = "-3.51393682670083E-19" ixz = "3.72260093121449E-20"
                iyy="0.0036112" iyz = "6.57163669546638E-20"
                izz="0.004721792" /> 
        </inertial>

        </link>

        <gazebo reference="support_link">
            <material>Gazebo/gray</material>
        </gazebo>


        <joint name="base_joint" type="fixed">
            <origin xyz="0 0 0.094" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="support_link" />
        </joint>


        <link name="laser">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="0.0375" length = "0.04"/>
                </geometry>
                <material name="black" />
            </visual>
       <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="0.0375" length = "0.04"/>
                </geometry>
       </collision>
            <cylinder_inertial_matrix  m="0.2" r="0.0375" h="0.04" />
        </link>

        <gazebo reference="laser">
            <material>Gazebo/Black</material>
        </gazebo>

<gazebo reference="laser">
           <sensor type="camera" name="camera_node">
                <update_rate>30.0</update_rate>
                <camera name="head">
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>1280</width>
                        <height>720</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="gazebo_camera" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>/camera</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
        </gazebo>


        <joint name="laser_joint" type="fixed">
            <origin xyz="0 0 0.188" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="laser" />
        </joint>
 
       
    </xacro:macro>

<xacro:xbot_support />

  <!-- Macro for robot xbot_base -->
    <xacro:macro name="xbot_base">

    <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>

        </link>

        <gazebo reference="base_footprint">
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 0.0975" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>
 
      <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.34 0.395 0.04" />
                </geometry>
                <material name="gray" />
            </visual>

            <collision>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                   <box size="0.34 0.395 0.04" />
                </geometry>
            </collision> 

        <inertial>
            <mass value="2" />
            <inertia ixx="0.07160115625" ixy = "-6.6980230317588E-19" ixz = "-2.21472363018394E-19"
                iyy="0.1249414625" iyz = "-4.29515715444313E-18"
                izz="0.05479390625" /> 
        </inertial>

        </link>
         <gazebo reference="base_link">
            <material>Gazebo/Blue</material>
        </gazebo>


        <!-- controller -->
        <gazebo>
            <plugin name="differential_drive_controller" 
                    filename="libgazebo_ros_diff_drive.so">
                <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>true</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>true</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <legacyMode>true</legacyMode>
                <leftJoint>left_front_wheel_joint</leftJoint>
                <rightJoint>right_front_wheel_joint</rightJoint>
                <leftJoint>left_back_wheel_joint</leftJoint>
                <rightJoint>right_back_wheel_joint</rightJoint>
                <wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
                <wheelDiameter>${2*wheel_radius}</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>1.8</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame> 
                <odometryTopic>odom</odometryTopic> 
                <robotBaseFrame>base_footprint</robotBaseFrame>
            </plugin>
        </gazebo> 

     
    </xacro:macro>
<xacro:xbot_base />
</robot>
