; Auto-generated. Do not edit!


(cl:in-package robot_move-msg)


;//! \htmlinclude moveFeedback.msg.html

(cl:defclass <moveFeedback> (roslisp-msg-protocol:ros-message)
  ((n_x
    :reader n_x
    :initarg :n_x
    :type cl:float
    :initform 0.0)
   (n_y
    :reader n_y
    :initarg :n_y
    :type cl:float
    :initform 0.0)
   (n_z
    :reader n_z
    :initarg :n_z
    :type cl:float
    :initform 0.0))
)

(cl:defclass moveFeedback (<moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_move-msg:<moveFeedback> is deprecated: use robot_move-msg:moveFeedback instead.")))

(cl:ensure-generic-function 'n_x-val :lambda-list '(m))
(cl:defmethod n_x-val ((m <moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_move-msg:n_x-val is deprecated.  Use robot_move-msg:n_x instead.")
  (n_x m))

(cl:ensure-generic-function 'n_y-val :lambda-list '(m))
(cl:defmethod n_y-val ((m <moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_move-msg:n_y-val is deprecated.  Use robot_move-msg:n_y instead.")
  (n_y m))

(cl:ensure-generic-function 'n_z-val :lambda-list '(m))
(cl:defmethod n_z-val ((m <moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_move-msg:n_z-val is deprecated.  Use robot_move-msg:n_z instead.")
  (n_z m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveFeedback>) ostream)
  "Serializes a message object of type '<moveFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'n_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'n_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'n_z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveFeedback>) istream)
  "Deserializes a message object of type '<moveFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'n_x) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'n_y) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'n_z) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveFeedback>)))
  "Returns string type for a message object of type '<moveFeedback>"
  "robot_move/moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveFeedback)))
  "Returns string type for a message object of type 'moveFeedback"
  "robot_move/moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveFeedback>)))
  "Returns md5sum for a message object of type '<moveFeedback>"
  "d56e8bdd8926891cb4120395ff64a44b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveFeedback)))
  "Returns md5sum for a message object of type 'moveFeedback"
  "d56e8bdd8926891cb4120395ff64a44b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveFeedback>)))
  "Returns full string definition for message of type '<moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 n_x~%float32 n_y~%float32 n_z~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveFeedback)))
  "Returns full string definition for message of type 'moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 n_x~%float32 n_y~%float32 n_z~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveFeedback>))
  (cl:+ 0
     4
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveFeedback
    (cl:cons ':n_x (n_x msg))
    (cl:cons ':n_y (n_y msg))
    (cl:cons ':n_z (n_z msg))
))
