; Auto-generated. Do not edit!


(cl:in-package robot_move-msg)


;//! \htmlinclude moveResult.msg.html

(cl:defclass <moveResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass moveResult (<moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_move-msg:<moveResult> is deprecated: use robot_move-msg:moveResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_move-msg:finish-val is deprecated.  Use robot_move-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveResult>) ostream)
  "Serializes a message object of type '<moveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveResult>) istream)
  "Deserializes a message object of type '<moveResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveResult>)))
  "Returns string type for a message object of type '<moveResult>"
  "robot_move/moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveResult)))
  "Returns string type for a message object of type 'moveResult"
  "robot_move/moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveResult>)))
  "Returns md5sum for a message object of type '<moveResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveResult)))
  "Returns md5sum for a message object of type 'moveResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveResult>)))
  "Returns full string definition for message of type '<moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveResult)))
  "Returns full string definition for message of type 'moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveResult
    (cl:cons ':finish (finish msg))
))
