// Generated by gencpp from file costmap_2d/DstarPoint.msg
// DO NOT EDIT!


#ifndef COSTMAP_2D_MESSAGE_DSTARPOINT_H
#define COSTMAP_2D_MESSAGE_DSTARPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costmap_2d
{
template <class ContainerAllocator>
struct DstarPoint_
{
  typedef DstarPoint_<ContainerAllocator> Type;

  DstarPoint_()
    : index()  {
    }
  DstarPoint_(const ContainerAllocator& _alloc)
    : index(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::costmap_2d::DstarPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_2d::DstarPoint_<ContainerAllocator> const> ConstPtr;

}; // struct DstarPoint_

typedef ::costmap_2d::DstarPoint_<std::allocator<void> > DstarPoint;

typedef boost::shared_ptr< ::costmap_2d::DstarPoint > DstarPointPtr;
typedef boost::shared_ptr< ::costmap_2d::DstarPoint const> DstarPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_2d::DstarPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_2d::DstarPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace costmap_2d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'costmap_2d': ['/home/zhang/catkin_learn/src/costmap_2d/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'map_msgs': ['/opt/ros/kinetic/share/map_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::costmap_2d::DstarPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_2d::DstarPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_2d::DstarPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_2d::DstarPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_2d::DstarPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_2d::DstarPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_2d::DstarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df62f201f3c7cdf0f85b4ec3adb4c299";
  }

  static const char* value(const ::costmap_2d::DstarPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf62f201f3c7cdf0ULL;
  static const uint64_t static_value2 = 0xf85b4ec3adb4c299ULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_2d::DstarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_2d/DstarPoint";
  }

  static const char* value(const ::costmap_2d::DstarPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_2d::DstarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] index\n\
";
  }

  static const char* value(const ::costmap_2d::DstarPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_2d::DstarPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DstarPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_2d::DstarPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_2d::DstarPoint_<ContainerAllocator>& v)
  {
    s << indent << "index[]" << std::endl;
    for (size_t i = 0; i < v.index.size(); ++i)
    {
      s << indent << "  index[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.index[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_2D_MESSAGE_DSTARPOINT_H
